[package]
name = "mp-stats-data-server"
version = "0.1.0"
edition = "2024"

[dependencies]
mp-stats-core = { workspace = true }
mp-stats-common = { workspace = true }
serde_json = { workspace = true }
smol_str = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
