[package]
name = "mp-stats-common"
version = "0.2.1"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }
lzma-rs = { workspace = true }
flate2 = { workspace = true }
thiserror = { workspace = true }
