[package]
name = "mp-stats-common"
version = "0.6.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }
lzma-rust2 = { workspace = true }
thiserror = { workspace = true }
