[package]
name = "mp-stats-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
smol_str = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
mp-stats-common = { path = "../common" }
