name: Build

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions:
  contents: read # Required to checkout the code

jobs:
  check:
    name: Check
    permissions:
      contents: read # Required to checkout the code
    uses: TimSchoenle/actions/.github/workflows/rust-cargo-check.yaml@db5bbe354aa20b8a5cf9800f689160c4c0f75256 # workflows-rust-cargo-check-v1.1.4

  test:
    name: Test
    permissions:
      contents: read # Required to checkout the code
    uses: TimSchoenle/actions/.github/workflows/rust-test.yaml@d681dc1bc16b10592a57a57d2845acbe97adb131 # workflows-rust-test-v1.0.1

  fmt:
    name: Auto Format
    uses: TimSchoenle/actions/.github/workflows/rust-auto-format.yaml@a7d92c33bdf0a2820fdecc6da9c986d5b9c36995 # workflows-rust-auto-format-v1.1.2
    secrets:
      APP_ID: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
      PRIVATE_KEY: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}

  clippy:
    name: Clippy
    permissions:
      contents: read # Required to checkout the code
      checks: write # Required to annotate the commit with clippy warnings
    uses: TimSchoenle/actions/.github/workflows/rust-clippy.yaml@0139849aaaac592ebf44af62ca1b469632172737 # workflows-rust-clippy-v1.1.2

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    needs: check
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-dependency-review
      cancel-in-progress: true
    if: github.event_name == 'pull_request'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Dependency Review
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4